project_id_env: CROWDIN_ID
api_token_env: CROWDIN_KEY
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /apps/mail/locales/en.json
    translation: /apps/mail/locales/%two_letters_code%.json
